# Generated by Django 6.0.3 on 2026-04-13 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='board_state',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='game',
            name='status',
            field=models.CharField(choices=[('ongoing', 'Ongoing'), ('checkmate', 'Checkmate'), ('draw', 'Draw')], default='ongoing', max_length=10),
        ),
        migrations.AddField(
            model_name='game',
            name='turn',
            field=models.CharField(choices=[('white', 'White'), ('black', 'Black')], default='white', max_length=10),
        ),
    ]
